import { Customer, Contact, Ticket, Interaction, Opportunity, Feedback, User, DashboardStats } from './types';

export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'شرکت آکمه',
    email: 'contact@acme.com',
    phone: '۰۲۱-۱۲۳۴۵۶۷۸',
    status: 'active',
    segment: 'enterprise',
    createdAt: '2024-01-15T10:00:00Z',
    lastInteraction: '2024-01-20T14:30:00Z',
    totalTickets: 12,
    satisfactionScore: 4.5,
  },
  {
    id: '2',
    name: 'راه‌حل‌های فناوری پارس',
    email: 'info@parstech.com',
    phone: '۰۲۱-۹۸۷۶۵۴۳۲',
    status: 'active',
    segment: 'small_business',
    createdAt: '2024-01-10T09:00:00Z',
    lastInteraction: '2024-01-18T16:45:00Z',
    totalTickets: 8,
    satisfactionScore: 4.2,
  },
  {
    id: '3',
    name: 'شرکت جهانی سپهر',
    email: 'support@sepehr.com',
    phone: '۰۲۱-۴۵۶۷۸۹۰۱',
    status: 'active',
    segment: 'enterprise',
    createdAt: '2024-01-05T11:00:00Z',
    lastInteraction: '2024-01-19T10:15:00Z',
    totalTickets: 15,
    satisfactionScore: 4.8,
  },
  {
    id: '4',
    name: 'فناوری نوین ایران',
    email: 'info@novintech.ir',
    phone: '۰۲۱-۵۵۵۱۲۳۴',
    status: 'active',
    segment: 'small_business',
    createdAt: '2024-01-08T13:00:00Z',
    lastInteraction: '2024-01-21T09:30:00Z',
    totalTickets: 6,
    satisfactionScore: 4.1,
  },
];

export const mockContacts: Contact[] = [
  {
    id: '1',
    customerId: '1',
    name: 'احمد محمدی',
    email: 'ahmad.mohammadi@acme.com',
    phone: '۰۹۱۲۳۴۵۶۷۸۹',
    role: 'مدیر فناوری اطلاعات',
    notes: 'مخاطب اصلی فنی',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    customerId: '1',
    name: 'سارا احمدی',
    email: 'sara.ahmadi@acme.com',
    phone: '۰۹۱۲۳۴۵۶۷۸۰',
    role: 'مدیرعامل',
    notes: 'تصمیم‌گیرنده اصلی',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '3',
    customerId: '2',
    name: 'علی رضایی',
    email: 'ali.rezaei@parstech.com',
    phone: '۰۹۱۲۳۴۵۶۷۸۱',
    role: 'مدیر فنی',
    notes: 'رهبر تیم فنی',
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: '4',
    customerId: '3',
    name: 'فاطمه کریمی',
    email: 'fatemeh.karimi@sepehr.com',
    phone: '۰۹۱۲۳۴۵۶۷۸۲',
    role: 'مدیر خرید',
    notes: 'مسئول خریدهای فناوری',
    createdAt: '2024-01-05T11:00:00Z',
  },
];

export const mockTickets: Ticket[] = [
  {
    id: '1',
    customerId: '1',
    customerName: 'شرکت آکمه',
    subject: 'مشکل ورود به سیستم',
    priority: 'high',
    status: 'open',
    assignedTo: 'علی جعفری',
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-01-20T09:00:00Z',
    description: 'کاربران با مشکل ورود به پورتال مواجه هستند',
    category: 'فنی',
  },
  {
    id: '2',
    customerId: '2',
    customerName: 'راه‌حل‌های فناوری پارس',
    subject: 'درخواست ویژگی جدید',
    priority: 'medium',
    status: 'in_progress',
    assignedTo: 'مریم احمدی',
    createdAt: '2024-01-18T14:30:00Z',
    updatedAt: '2024-01-19T10:15:00Z',
    description: 'درخواست برای ویژگی گزارش‌گیری جدید',
    category: 'بهبود',
  },
  {
    id: '3',
    customerId: '3',
    customerName: 'شرکت جهانی سپهر',
    subject: 'مشکل خروجی داده',
    priority: 'low',
    status: 'closed',
    assignedTo: 'حسن محمدی',
    createdAt: '2024-01-17T11:00:00Z',
    updatedAt: '2024-01-19T16:45:00Z',
    description: 'مشکل در عملکرد خروجی CSV',
    category: 'فنی',
  },
  {
    id: '4',
    customerId: '4',
    customerName: 'فناوری نوین ایران',
    subject: 'آموزش کاربران',
    priority: 'medium',
    status: 'open',
    assignedTo: 'زهرا کریمی',
    createdAt: '2024-01-21T08:00:00Z',
    updatedAt: '2024-01-21T08:00:00Z',
    description: 'درخواست جلسه آموزشی برای کاربران جدید',
    category: 'آموزش',
  },
];

export const mockInteractions: Interaction[] = [
  {
    id: '1',
    customerId: '1',
    customerName: 'شرکت آکمه',
    type: 'email',
    subject: 'پیگیری پیاده‌سازی',
    description: 'بحث در مورد زمان‌بندی و الزامات پیاده‌سازی',
    date: '2024-01-20T14:30:00Z',
    outcome: 'مثبت',
  },
  {
    id: '2',
    customerId: '2',
    customerName: 'راه‌حل‌های فناوری پارس',
    type: 'phone',
    subject: 'تماس پشتیبانی فنی',
    description: 'حل مشکلات پیکربندی',
    date: '2024-01-18T16:45:00Z',
    duration: 30,
    outcome: 'حل شده',
  },
  {
    id: '3',
    customerId: '3',
    customerName: 'شرکت جهانی سپهر',
    type: 'meeting',
    subject: 'بررسی فصلی کسب‌وکار',
    description: 'بحث در مورد معیارهای عملکرد و نقشه راه آینده',
    date: '2024-01-19T10:15:00Z',
    duration: 60,
    outcome: 'مثبت',
  },
  {
    id: '4',
    customerId: '4',
    customerName: 'فناوری نوین ایران',
    type: 'email',
    subject: 'ارسال مستندات',
    description: 'ارسال راهنمای کاربری و مستندات فنی',
    date: '2024-01-21T09:30:00Z',
    outcome: 'تحویل شده',
  },
];

export const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    customerId: '1',
    customerName: 'شرکت آکمه',
    title: 'تمدید لایسنس سازمانی',
    value: 150000,
    stage: 'proposal',
    probability: 80,
    expectedCloseDate: '2024-03-15',
    assignedTo: 'علی جعفری',
    createdAt: '2024-01-15T10:00:00Z',
    notes: 'تمدید سالانه با امکان گسترش',
  },
  {
    id: '2',
    customerId: '2',
    customerName: 'راه‌حل‌های فناوری پارس',
    title: 'لایسنس‌های کاربری اضافی',
    value: 45000,
    stage: 'negotiation',
    probability: 70,
    expectedCloseDate: '2024-02-28',
    assignedTo: 'مریم احمدی',
    createdAt: '2024-01-10T09:00:00Z',
    notes: 'گسترش اندازه تیم',
  },
  {
    id: '3',
    customerId: '3',
    customerName: 'شرکت جهانی سپهر',
    title: 'بسته پشتیبانی ویژه',
    value: 75000,
    stage: 'qualified',
    probability: 60,
    expectedCloseDate: '2024-04-01',
    assignedTo: 'حسن محمدی',
    createdAt: '2024-01-05T11:00:00Z',
    notes: 'علاقه‌مند به پشتیبانی ۲۴/۷',
  },
  {
    id: '4',
    customerId: '4',
    customerName: 'فناوری نوین ایران',
    title: 'ماژول گزارش‌گیری پیشرفته',
    value: 25000,
    stage: 'lead',
    probability: 40,
    expectedCloseDate: '2024-05-15',
    assignedTo: 'زهرا کریمی',
    createdAt: '2024-01-08T13:00:00Z',
    notes: 'نیاز به گزارش‌گیری تخصصی',
  },
];

export const mockFeedback: Feedback[] = [
  {
    id: '1',
    customerId: '1',
    customerName: 'شرکت آکمه',
    type: 'csat',
    score: 4.5,
    comment: 'خدمات و پشتیبانی عالی',
    createdAt: '2024-01-20T15:00:00Z',
    category: 'پشتیبانی',
  },
  {
    id: '2',
    customerId: '2',
    customerName: 'راه‌حل‌های فناوری پارس',
    type: 'nps',
    score: 9,
    comment: 'قطعاً به دیگران توصیه می‌کنم',
    createdAt: '2024-01-18T17:00:00Z',
    category: 'محصول',
  },
  {
    id: '3',
    customerId: '3',
    customerName: 'شرکت جهانی سپهر',
    type: 'csat',
    score: 5,
    comment: 'پلتفرم و تیم فوق‌العاده',
    createdAt: '2024-01-19T11:00:00Z',
    category: 'کلی',
  },
  {
    id: '4',
    customerId: '4',
    customerName: 'فناوری نوین ایران',
    type: 'csat',
    score: 4.2,
    comment: 'رابط کاربری بهتری نیاز است',
    createdAt: '2024-01-21T10:00:00Z',
    category: 'محصول',
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'علی جعفری',
    email: 'ali.jafari@company.com',
    role: 'admin',
    avatar: 'ع.ج',
    lastActive: '2024-01-20T16:00:00Z',
    status: 'active',
    team: 'پشتیبانی',
  },
  {
    id: '2',
    name: 'مریم احمدی',
    email: 'maryam.ahmadi@company.com',
    role: 'agent',
    avatar: 'م.ا',
    lastActive: '2024-01-20T15:30:00Z',
    status: 'active',
    team: 'فروش',
  },
  {
    id: '3',
    name: 'حسن محمدی',
    email: 'hassan.mohammadi@company.com',
    role: 'manager',
    avatar: 'ح.م',
    lastActive: '2024-01-20T14:45:00Z',
    status: 'active',
    team: 'پشتیبانی',
  },
  {
    id: '4',
    name: 'زهرا کریمی',
    email: 'zahra.karimi@company.com',
    role: 'agent',
    avatar: 'ز.ک',
    lastActive: '2024-01-20T13:20:00Z',
    status: 'active',
    team: 'آموزش',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalCustomers: 156,
  activeCustomers: 142,
  openTickets: 23,
  avgSatisfactionScore: 4.3,
  npsScore: 68,
  totalOpportunities: 45,
  monthlyRevenue: 2450000,
  ticketResolutionTime: 2.5,
};

export const mockChartData = {
  salesTrend: {
    labels: ['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'],
    datasets: [
      {
        label: 'درآمد',
        data: [1200000, 1350000, 1150000, 1450000, 1600000, 1750000, 1900000, 2100000, 2250000, 2400000, 2350000, 2450000],
        borderColor: '#00BCD4',
        backgroundColor: 'rgba(0, 188, 212, 0.1)',
        tension: 0.4,
      },
    ],
  },
  customerSatisfaction: {
    labels: ['بسیار راضی', 'راضی', 'خنثی', 'ناراضی', 'بسیار ناراضی'],
    datasets: [
      {
        data: [45, 35, 12, 6, 2],
        backgroundColor: ['#4CAF50', '#8BC34A', '#FFC107', '#FF9800', '#F44336'],
        borderWidth: 0,
      },
    ],
  },
  teamPerformance: {
    labels: ['پشتیبانی', 'فروش', 'موفقیت', 'مهندسی'],
    datasets: [
      {
        label: 'تیکت‌های حل شده',
        data: [85, 72, 68, 45],
        backgroundColor: '#00BCD4',
        borderRadius: 8,
      },
    ],
  },
};